"""Add collections table

Revision ID: 4cb81ed6a997
Revises: 7ab64ab616c7
Create Date: 2026-09-26 23:29:24.186960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb81ed6a997'
down_revision: Union[str, None] = '7ab64ab616c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_org_id'), 'collections', ['org_id'], unique=False)
    op.create_index(op.f('ix_collections_workspace_id'), 'collections', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'collections', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_collections_workspace_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_org_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
