"""Remove reports topics and extraction tables

Revision ID: 7ab64ab616c7
Revises: 001_initial_schema
Create Date: 2026-09-26 18:10:59.200442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ab64ab616c7'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_drafts_job_id'), table_name='report_drafts')
    op.drop_index(op.f('ix_report_drafts_org_id'), table_name='report_drafts')
    op.drop_index(op.f('ix_report_drafts_workspace_id'), table_name='report_drafts')
    op.drop_table('report_drafts')
    op.drop_index(op.f('ix_topic_results_job_id'), table_name='topic_results')
    op.drop_index(op.f('ix_topic_results_org_id'), table_name='topic_results')
    op.drop_index(op.f('ix_topic_results_workspace_id'), table_name='topic_results')
    op.drop_table('topic_results')
    op.drop_index(op.f('ix_extracted_facts_document_id'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_document_version_id'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_metric'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_mine_name'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_subsidiary_name'), table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index(op.f('ix_chunks_tsv'), table_name='chunks', postgresql_using='gin')
    op.drop_constraint(op.f('chunks_document_version_id_fkey'), 'chunks', type_='foreignkey')
    op.drop_constraint(op.f('chunks_document_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'document_versions', ['document_version_id'], ['id'])
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'])
    op.drop_column('chunks', 'tsv')
    op.alter_column('document_metadata', 'detected_dates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=True)
    op.alter_column('document_metadata', 'detected_subsidiary_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=True)
    op.alter_column('document_metadata', 'detected_mine_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=True)
    op.alter_column('document_metadata', 'language',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.drop_constraint(op.f('document_metadata_document_version_id_fkey'), 'document_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'document_metadata', 'document_versions', ['document_version_id'], ['id'])
    op.drop_column('document_metadata', 'created_at')
    op.alter_column('document_versions', 'file_ref',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('document_versions', 'detected_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_constraint(op.f('document_versions_document_id_fkey'), 'document_versions', type_='foreignkey')
    op.create_foreign_key(None, 'document_versions', 'documents', ['document_id'], ['id'])
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('pages', 'source_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('pages_document_version_id_fkey'), 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'document_versions', ['document_version_id'], ['id'])
    op.drop_column('pages', 'created_at')
    op.drop_constraint(op.f('processing_jobs_document_version_id_fkey'), 'processing_jobs', type_='foreignkey')
    op.drop_constraint(op.f('processing_jobs_document_id_fkey'), 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_jobs', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'processing_jobs', 'document_versions', ['document_version_id'], ['id'])
    op.alter_column('sections', 'section_path',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_index(op.f('ix_sections_section_path'), table_name='sections')
    op.drop_constraint(op.f('sections_document_version_id_fkey'), 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'document_versions', ['document_version_id'], ['id'])
    op.drop_column('sections', 'summary')
    op.drop_column('sections', 'created_at')
    op.alter_column('tables', 'header_row',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tables', 'raw_cells',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(op.f('tables_document_version_id_fkey'), 'tables', type_='foreignkey')
    op.create_foreign_key(None, 'tables', 'document_versions', ['document_version_id'], ['id'])
    op.drop_column('tables', 'created_at')
    op.drop_column('tables', 'section_path')
    op.drop_column('tables', 'structure')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('section_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.create_foreign_key(op.f('tables_document_version_id_fkey'), 'tables', 'document_versions', ['document_version_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tables', 'raw_cells',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('tables', 'header_row',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('sections', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('sections', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key(op.f('sections_document_version_id_fkey'), 'sections', 'document_versions', ['document_version_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_sections_section_path'), 'sections', ['section_path'], unique=False)
    op.alter_column('sections', 'section_path',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_constraint(None, 'processing_jobs', type_='foreignkey')
    op.drop_constraint(None, 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('processing_jobs_document_id_fkey'), 'processing_jobs', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('processing_jobs_document_version_id_fkey'), 'processing_jobs', 'document_versions', ['document_version_id'], ['id'], ondelete='CASCADE')
    op.add_column('pages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key(op.f('pages_document_version_id_fkey'), 'pages', 'document_versions', ['document_version_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pages', 'source_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('documents', 'filename',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.create_foreign_key(op.f('document_versions_document_id_fkey'), 'document_versions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('document_versions', 'detected_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('document_versions', 'file_ref',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.add_column('document_metadata', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_metadata', type_='foreignkey')
    op.create_foreign_key(op.f('document_metadata_document_version_id_fkey'), 'document_metadata', 'document_versions', ['document_version_id'], ['id'], ondelete='CASCADE')
    op.alter_column('document_metadata', 'language',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('document_metadata', 'detected_mine_names',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('document_metadata', 'detected_subsidiary_names',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('document_metadata', 'detected_dates',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('chunks', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, text)", persisted=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_document_id_fkey'), 'chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chunks_document_version_id_fkey'), 'chunks', 'document_versions', ['document_version_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_chunks_tsv'), 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('extracted_facts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('table_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('metric', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('metric_raw_label', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('value', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('unit_normalized', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('mine_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('subsidiary_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('coal_grade', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('period_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('period_value', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('extraction_method', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('validation_flag', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('extracted_facts_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('extracted_facts_document_version_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('extracted_facts_table_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('extracted_facts_pkey'))
    )
    op.create_index(op.f('ix_extracted_facts_subsidiary_name'), 'extracted_facts', ['subsidiary_name'], unique=False)
    op.create_index(op.f('ix_extracted_facts_mine_name'), 'extracted_facts', ['mine_name'], unique=False)
    op.create_index(op.f('ix_extracted_facts_metric'), 'extracted_facts', ['metric'], unique=False)
    op.create_index(op.f('ix_extracted_facts_document_version_id'), 'extracted_facts', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_extracted_facts_document_id'), 'extracted_facts', ['document_id'], unique=False)
    op.create_table('topic_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('word_cloud_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_results_pkey'))
    )
    op.create_index(op.f('ix_topic_results_workspace_id'), 'topic_results', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_topic_results_org_id'), 'topic_results', ['org_id'], unique=False)
    op.create_index(op.f('ix_topic_results_job_id'), 'topic_results', ['job_id'], unique=True)
    op.create_table('report_drafts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('file_ref', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('report_drafts_pkey'))
    )
    op.create_index(op.f('ix_report_drafts_workspace_id'), 'report_drafts', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_report_drafts_org_id'), 'report_drafts', ['org_id'], unique=False)
    op.create_index(op.f('ix_report_drafts_job_id'), 'report_drafts', ['job_id'], unique=True)
    # ### end Alembic commands ###
